export default function service(req, res) {
    res.status(200).json([
        {
            "id":1,
            "title":"tt",
            "dec":"dec"
        },
        {
            "id":2,
            "title":"tt",
            "dec":"dec"
        },
        {
            "id":3,
            "title":"tt",
            "dec":"dec"
        },
        {
            "id":4,
            "title":"tt",
            "dec":"dec"
        }
    ]
    )
  }